title: "Decision Making in Reinforcement Learning"
description: "Poster companion: robust decision making frameworks for RL agents."
url: "https://iman1234ahmadi.github.io"
baseurl: "/Decision-Transformer" # repo name for GitHub Pages project site


# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# Sass config: reduce noise from theme deprecations
sass:
  quiet_deps: true
  style: compressed
  sourcemap: never


# Socials (optional)
author:
name: "Iman Ahmadi & Amirreza Tanevardi"
email: "iman1234ahmadi@gmail.com & amirreza.tanevardi@gmail.com"


# Markdown + syntax
markdown: kramdown
kramdown:
input: GFM
math_engine: mathjax


# Collections (future-proofing if you add more posts/pages)
collections:
  posts:
    output: true
    permalink: /:title/


# Defaults (adds custom CSS + MathJax to all pages)
defaults:
  - scope:
      path: ""
    values:
      layout: default
# Include assets explicitly (optional)
include:
  - assets/css/style.css
  - assets/js/reveal.js
